### ISSUE TITLE
Make cosmic ray compatible with approval testing

### ISSUE THREAD

**Issue by emilybache** [sixty-north/cosmic-ray#386] opened 2018-08-23 07:52 UTC
I have a test suite using approval testing which doesn't work with cosmic ray. It gives me a stack trace (below). The stack trace points at something going wrong while running the mutants through the test suite, the json database of results gets corrupted.

I suspect the problem is due to me using Approval testing although I'm not sure how that could have caused this. I'm just working on the assumption no-one has used this tool this way before. Approval testing works by the test case creating a 'received' file in the current working directory and diffing it against the 'approved' file. If they differ, the test fails. This can't work properly if tests are running in parallel, they will keep overwriting the same received file. Could that explain this error? 

This code is a nice little exercise I use for teaching and the tests as they are in this example have 100% line coverage but not 100% mutation coverage. I'm expecting cosmic ray to point out lines 18-23: I already know mutants in these lines will not be killed by these tests.

cosmic-ray exec my_session
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/cosmic-ray", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cosmic_ray/cli.py", line 363, in main
    exit_at_end=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
    result = commands(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 147, in __call__
    return handler(config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cosmic_ray/cli.py", line 178, in handle_exec
    cosmic_ray.commands.execute(session_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cosmic_ray/progress.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cosmic_ray/commands/execute.py", line 48, in execute
    work_db.update_work_item(work_item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cosmic_ray/work_db.py", line 158, in update_work_item
    tinydb.Query().job_id == work_item.job_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tinydb/database.py", line 493, in update
    cond, doc_ids
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tinydb/database.py", line 339, in process_elements
    self._write(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tinydb/database.py", line 385, in _write
    self._storage.write(values)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tinydb/database.py", line 111, in write
    self._storage.write(raw_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tinydb/storages.py", line 112, in write
    serialized = json.dumps(data, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'JSONDecodeError' is not JSON serializable

**Comment by emilybache** [comment] 2018-08-23 07:57
I put the files in a gist:

https://gist.github.com/emilybache/85fc473e008f8ceec38e0ef616fe2312

**Comment by abingham** [comment] 2018-08-23 13:31
Hi Emily! It's exciting to see CR being used with approval. The problem you're seeing is almost certainly that a worker subprocess (i.e. a subprocess that performs a single mutations and runs a test) is printing something to stdout which is not valid JSON. We parse that output to determine how the worker behaved.

Are you using the newest version of CR? We have some handling for this case in more recent versions.

I'll do my best to help you get this sorted out, but I'm traveling right now so my bandwidth is pretty limited for the next few weeks.

**Comment by emilybache** [comment] 2018-08-23 14:51
> cosmic-ray --version
Cosmic Ray 3.1.2

I just did pip install, nothing fancy

**Comment by Neppord** [comment] 2018-08-24 14:18
@abingham your guess that it was output that made it fail was correct. Setting the diff-tool to the linux command `true` worked and i was able to use it with approvaltests.

I think however that this should not need to be done, its confusing. Could a fix be implemented or is it impossible?

**Comment by emilybache** [comment] 2018-08-24 14:55
just to clarify @Neppord 's comment - in the gist, replace '/usr/bin/diff' with 'true' and cosmic-ray works. So the problem is to do with how approval tests is handling failing test results.

**Comment by abingham** [comment] 2018-08-26 14:51
We can probably find a fix, though it'll be a while before I can look into
it. Ultimately, if running the tests prints to stout, it's going to confuse
CR. You might need to write a new test-runner plugin, but I'm not sure.
I'll be able to give better support in a few weeks when I'm back from
travel.

**Comment by abingham** [comment] 2018-08-26 14:52
I'll also add that I'm quite interested in getting this to work.

**Comment by abingham** [comment] 2018-09-10 09:15
I've had a look at this, and the problem is that approval is generating stdout output that cosmic-ray can't intercept. CR worker processes (i.e. the subprocesses that perform a single mutation and test run) redirects their stdout to `os.devnull` by default. They determine the outcome of the tests via the testing framework's programmatic interface, and stdout is treated as irrelevant. The stdout from the worker subprocess is supposed to only include the JSON dump of the results (in the form of a `WorkItem`).

However, approval seems to be launching subprocesses of its own (e.g. in `GenericDiffReporter.run_command`), and - from the point of view of the `cosmic-ray exec` command - the stdout of these processes is intermingled with the stdout of the worker. This extra output is the proximal cause of the problems you're seeing.

There may be clever ways around this that we can implement entirely in CR, but I'm not sure. It would be onerous for CR to require all testing frameworks to not generate any stdout from subprocesses. Perhaps we just need some sort out frame/demarcation for the worker's JSON output that we can use to identify it.

**Comment by rob-smallshire** [comment] 2018-09-11 04:54
Can Cosmic-Ray use another pipe instead of stdout for capturing its own output and leave stdout for testing frameworks to use?

**Comment by abingham** [comment] 2018-09-11 08:18
Possibly, I'll need to look at the subprocess API to see what's possible. That would be a nice, clean solution.

**Comment by abingham** [comment] 2018-09-11 09:34
[this is mostly a note to myself] Recent versions of CR are better about catching JSON decode errors like this and marking the mutants as incompetent. So if you use these recent version for sorting out this issue, you *won't* see the traceback; instead you'll see a lot of incompetent mutants.

**Comment by abingham** [comment] 2018-09-11 10:41
@rob-smallshire As a quick experiment, I passed a temporary file as the `stdout` argument to `subprocess.Popen`, but this file still contained the output of the sub-subprocess.

**Comment by abingham** [comment] 2018-09-11 11:26
I've moved the discussion of how to best get results from workers to issue #391.

**Comment by abingham** [comment] 2018-09-14 08:34
@emilybache Try out the [`isolated-result-passing` branch](https://github.com/sixty-north/cosmic-ray/tree/isolated-result-passing). It uses `multiprocessing` pipes rather than stdout to communicate results from workers, meaning that "extra" output on stdout is irrelevant.

**Comment by abingham** [comment] 2018-09-15 09:17
@emilybache I merged that branch into master, so master should now work with approval (or at least with the gist that you initially posted). I've tried it out with the gist, and it all seems to work for me. But if you're still seeing problems we can work through them here.

**Closed** 2018-10-22 18:27 UTC
